---
title: "Readying sustainable aquaculture for a changing ocean: uncovering the mechanisms associated with intergenerational carryover effects to enhance bivalve resilience to acidification"
subtitle: Annual Report
author: Steven Roberts
date: "`r format(Sys.time(), '%d %B, %Y')`"  
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

## Activity

The core activity supported by this grant was the development of an interdisciplinary unit on shellfish aquaculture. The bulk of the planning for this project took place during Summer 2022 in collaboration with teachers from Maritime High School (MHS) in Des Moines, WA, members of the Roberts lab, and a variety of community collaborators from industry, research, and government. As a result of this project, we produced a detailed unit plan and a range of supporting materials, including lesson plans, and implemented the project with 40 10^th^ graders in Fall 2022. Students presented their final projects to a live and virtual audience in November, 2022. We gathered feedback from members of the audience, partners we worked with during the course of the project, and students, about what aspects of the project were successful and where people saw room for improvement. As a result of this feedback, we have developed a revised unit plan. In addition to revising the timeline for the field work experiences that form the major off-campus learning for the project, we have also identified opportunities to work more effectively with some of the partners to build cohesive lessons.

One of the major improvements we are planning for next year is to build out a series of more robust genetics lessons. This topic was covered in several on-campus lessons and during some of the field work experiences, but we would like to make it a more central part of the unit. To accomplish this, we are working with a team from NOAA Fisheries and the Roberts Lab to design a set of lessons about identifying fish sex from DNA, which will not only bridge the portion of the unit that focuses on fin fish with that focusing on shellfish, but will also provide a unifying thread between off-campus field work experiences as well as provide students with the background knowledge required to more effectively develop their final project ideas. This work is planned to conclude by May 31.

In addition to contributing to the development of this project, I have been working on a number of other projects to facilitate opportunities for students at MHS, increase collaboration between the scientific community in our area and this school, and support other outreach efforts happening at UW. With support from members of the Roberts Lab, we have developed (or are developing) several multi-day lessons to teach students about coastal erosion and living coastlines (which we implemented with the MHS 10^th^ graders and furthered their learning from the shellfish unit), the effect of marine heatwaves on marine organisms (which will also fit in with the other content from the shellfish unit), and a scientific writing workshop for 9^th^ graders. I have also either developed or contributed to several other marine science curriculum efforts, including Puget Sound Oceanography and \"Science on a Boat\", which will support students doing independent research while working on small boats in local waterways. We worked with members of the Padilla-Gamino lab in UW SAFS to set up a lab tour and help 43 9^th^ grade students learn about cutting edge microplastics research (January 26, 2023). We used this tour to develop a document outlining features of a good lab tour, which we shared with the UW SAFS \"Students Exploring Aquatic Sciences\" (SEAS) outreach group. In addition, I have been working with the SEAS group to expand their library of outreach lesson plans, as well as creating a template for them to use in designing new lessons to encourage student centered learning as well as effective communication with partner teachers.

Finally, I have presented to multiple external research groups, including NOAA Fisheries Physiology group (March 3, 2023) and NANOOS (January 27, 2023). I also presented the Banse Early Career Scientist Seminar on January 25 at the UW School of Oceanography, about the work we are doing with Maritime High School and how to create sustained partnerships between the science and K12 communities. The latter seminar had a combined live/virtual audience of roughly 40 members of the UW SoO community.
